name: ClearLagg
main: ClearLagg\Loader
version: 1.1.0
api: 
- 1.12.0
- 1.13.0
- 2.0.0
- 3.0.0-ALPHA1

author: Applecart_Starfury
website: https://github.com/starfury1927
description: "좀비 플러그인 부활 프로젝트"
permissions:
  clearlagg:
    default: false
    description: "클리어렉 플러그인 접근명령어"
    children:
      clearlagg.command:
        default: false
        description: "클리어렉 플러그인 접근명령어"
        children:  
          clearlagg.command.clearlagg:
            default: op
            description: "클리어렉 플러그인 접근명령어 [오피용]"
